server:
  port: ${PORT:8080}
  #이거 덕분에 mustache 한글 됨.
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
  forward-headers-strategy: native


jwt:
  access_token_expiration_time: 900 #15분초
  refresh_token_expiration_time: 604800
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,httptrace,metrics"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0  # 100% 요청 추적

spring:
  application:

#  jwt:
#    access-secret: l$Nn8x3f@9Z*P1o&uK4R6^T#mGwQ%7Yv
#    refresh-secret: mA*9R6T#yP2Z$L&Nn3vG^X1Kw%8oG7Qf
#    access-expiration: 600000  # 10 min: 10 * 60 * 1000 milliseconds
#    refresh-expiration: 10800000

  profiles:
    active: local

  mustache:
    charset: UTF-8
  mvc:
    static-path-pattern: "/**" #모든 정적 자원 서빙 가능
    view:
      encoding: UTF-8



  # h2 세팅
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

   # 3 hours: 3 * 60 * 60 * 1000 milliseconds

  data:
    redis:
      host: localhost # 로컬에서 테스트 할 때는 localhost로 사용 redis
      port: 6379

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

# MySql
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/transSys?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: aivle202406


    #    database-platform: org.hibernate.community.dialect.SQLiteDialect
#    hibernate:
#      ddl-auto: update # update
#  datasource:
#    url: jdbc:sqlite:src/main/resources/database/em.db
#    driver-class-name: org.sqlite.JDBC
#    username: ""
#    password: ""


# Python API 서버..
#hospital:
#  api:
#    host: http://127.0.0.1:8000