server:
  port: ${PORT:8080}
  #이거 덕분에 mustache 한글 됨.
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true

spring:
  application:
    name: Pj
  mustache:
    charset: UTF-8
  mvc:
    view:
      encoding: UTF-8

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jpa:
    #    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update # update
#  datasource:
#    url: jdbc:sqlite:src/main/resources/database/em.db
#    driver-class-name: org.sqlite.JDBC
#    username: ""
#    password: ""


# Python API 서버..
#hospital:
#  api:
#    host: http://127.0.0.1:8000